apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20231226185600.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20231226185600.0.0+build.02e9424
  releaseNotes: |
    Release v20231226185600.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-24-12-2023-01-25-47-560728337/where-for-dinner-ui-my-apps-bundle@sha256:105562643514c48bbf16e823faf239ac70ac263d51ff8cc4fd6eeaf913c756f8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

