apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20231226185214.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20231226185214.0.0+build.02e9424
  releaseNotes: |
    Release v20231226185214.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-24-12-2023-01-25-47-560728337/where-for-dinner-my-apps-bundle@sha256:4561bcce7dd777af834b5311b9694718a25461ab8f7082c29fd63282a06f44ca
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

